<?php 
	$this->load->view('Home/inc/frame');
	$this->load->view('Home/inc/right');
	$this->load->view('Home/inc/logo');
	$this->load->view('Home/inc/image');
	$this->load->view('Home/content');
	$this->load->view('Home/inc/footer');
	$this->load->view('Home/inc/loadScripts');
?>